### ISSUE TITLE
Actividad 1: Infografía

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-1-infografia-MarcoRg06#1]
Nombre: Marco Uriel Rosas García.
Actividad 1: Infografia.
![Infografia_Marco Uriel Rosas Garcia1 (Infografía)](https://github.com/user-attachments/assets/942d69be-97c1-467d-952b-86fb591ad02f)
![Infografia_Marco Uriel Rosas Garcia1 (Bibliografía)](https://github.com/user-attachments/assets/caa9038a-6c4a-491c-ac36-57674e7b4fb6)

**Comment by Anakimberly** [comment]
Obtuviste el 20% cuenta con todos los criterios especificados en la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
